cabal-version:      3.0
name:               bsc
version:            2024.3.0
synopsis:          Bluespec Compiler
description:       The Bluespec Compiler (BSC) is a compiler and simulator for the Bluespec Hardware Description Language.
homepage:          https://github.com/B-Lang-org/bsc
bug-reports:       https://github.com/B-Lang-org/bsc/issues
license:           BSD-3-Clause
license-file:      LICENSE.txt
author:            Bluespec Inc.
maintainer:        B-Lang Maintainers
category:          Hardware
build-type:        Simple
extra-doc-files:   README.md
                   INSTALL.md
                   DEVELOP.md
tested-with:       GHC == 9.4.7
extra-source-files: testsuite/config/*.tcl
                   , testsuite/lib/*.exp
                   , testsuite/bsc.evaluator/**/*.exp
                   , testsuite/bsc.typechecker/**/*.exp
                   , testsuite/bsc.lib/**/*.exp
                   , testsuite/bsc.if/**/*.exp
                   , testsuite/bsc.names/**/*.exp
                   , testsuite/bsc.bluetcl/**/*.exp
                   , testsuite/bsc.interra/**/*.exp
                   , testsuite/bsc.bluesim/**/*.exp
                   , testsuite/bsc.bugs/bluespec_inc/**/*.exp
                   , testsuite/bsc.bugs/github/**/*.exp
                   , testsuite/bsc.bugs/pre_bluespec_inc/**/*.exp
                   , testsuite/site.exp

common common-options
    default-language: Haskell2010
    ghc-options:      -Wall
                      -Wcompat
                      -Widentities
                      -Wno-incomplete-uni-patterns
                      -Wno-incomplete-record-updates
                      -fno-warn-orphans
                      -fno-warn-name-shadowing
                      -fno-warn-unused-matches
    if impl(ghc >= 8.0)
        ghc-options:    -Wredundant-constraints
    if impl(ghc >= 8.2)
        ghc-options:    -fhide-source-paths
    if impl(ghc >= 8.4)
        ghc-options:    -Wmissing-export-lists
                        -Wpartial-fields
    if impl(ghc >= 8.10)
        ghc-options:    -Wunused-packages

library
    import:           common-options
    hs-source-dirs:   src/comp
                      src/Libraries
                      src/comp/Libs
                      src/vendor/yices/v2.6/HaskellIfc
                      src/vendor/stp/HaskellIfc
                      src/vendor/htcl
                      src/comp/GHC/posix
                      src/comp/Parser/BSV
    build-depends:    base ==4.13.0.0
                   , array ==0.5.4.0
                   , containers ==0.6.2.1
                   , directory ==1.3.6.0
                   , filepath ==1.4.2.1
                   , mtl ==2.2.2
                   , parsec >=3.1.14.0 && <3.2
                   , process ==1.6.9.0
                   , syb ==0.7.2.4
                   , unix ==2.7.2.2
                   , split ==0.2.5
                   , text ==1.2.4.0
                   , bytestring ==0.10.10.1
                   , regex-compat ==0.95.2.2
                   , old-time ==1.1.0.4
                   , time ==1.9.3
                   , integer-gmp ==1.0.2.0
                   , gitrev >=1.3.1
    exposed-modules:  BSC
                   , Util
                   , VCD
                   , VFileName
                   , VFinalCleanup
                   , VIOProps
                   , VModInfo
                   , VPIWrappers
                   , VPrims
                   , VVerilogDollar
                   , Verilog
                   , Version
                   , Wires
                   , TCMisc
                   , TCPat
                   , TCheck
                   , TIMonad
                   , TclUtils
                   , TopUtils
                   , Type
                   , TypeAnalysis
                   , TypeAnalysisTclUtil
                   , TypeCheck
                   , TypeOps
                   , Undefined
                   , SimPrimitiveModules
                   , Simplify
                   , SpeedyString
                   , StdPrel
                   , Subst
                   , SymTab
                   , Synthesize
                   , SystemCWrapper
                   , SystemCheck
                   , SimCCBlock
                   , SimCOpt
                   , SimDomainInfo
                   , SimExpand
                   , SimFileUtils
                   , SimMakeCBlocks
                   , SimPackage
                   , SimPackageOpt
                   , Pretty
                   , Prim
                   , ProofObligation
                   , RSchedule
                   , RealUtil
                   , SAL
                   , SAT
                   , SATPred
                   , SCC
                   , SEMonad
                   , SchedInfo
                   , Scheme
                   , SignalNaming
                   , SimBlocksToC
                   , PoisonUtils
                   , Position
                   , Pragma
                   , PragmaCheck
                   , PreIds
                   , PreStrings
                   , Pred
                   , Pred2STP
                   , Pred2Yices
                   , PVPrint
                   , Params
                   , ParseOp
                   , Lex
                   , Literal
                   , Log2
                   , MakeSymTab
                   , PFPrint
                   , PPrint
                   , IWireSet
                   , Id
                   , IdPrint
                   , IfcBetterInfo
                   , InferKind
                   , InlineCReg
                   , InlineReg
                   , ABin
                   , ABinUtil
                   , AConv
                   , ADumpScheduleInfo
                   , AExpand
                   , AExpr2STP
                   , AExpr2Util
                   , AExpr2Yices
                   , AOpt
                   , AScheduleInfo
                   , ASyntax
                   , ASyntaxUtil
                   , AUses
                   , AVerilogUtil
                   , Assump
                   , BDD
                   , BExpr
                   , Backend
                   , BackendNamingConventions
                   , Bag
                   , Balanced
                   , BinData
                   , BoolExp
                   , BoolOpt
                   , BuildVersion
                   , CCSyntax
                   , CFreeVars
                   , CSubst
                   , CSyntax
                   , CSyntaxTypes
                   , CSyntaxUtil
                   , CType
                   , CVPrint
                   , Classic
                   , ConTagInfo
                   , ContextErrors
                   , CtxRed
                   , Error
                   , ErrorMonad
                   , ErrorUtil
                   , Eval
                   , FStringCompat
                   , FileIOUtil
                   , FileNameUtil
                   , Fixity
                   , Flags
                   , ForeignFunctions
                   , GHCPretty
                   , GenABin
                   , GenWrapUtils
                   , GraphMap
                   , GraphUtil
                   , GraphWrapper
                   , IConv
                   , IConvLet
                   , IInline
                   , IInlineUtil
                   , IOMutVar
                   , IPrims
                   , IStateLoc
                   , ISyntax
                   , ISyntaxUtil
                   , ITransform
                   , IType
                   , InstNodes
                   , IntLit
                   , IntegerUtil
                   , Intervals
                   , KIMisc
                   , LambdaCalcUtil
                   , SystemVerilogKeywords
                   , SystemVerilogTokens
                   , Unify
                   , IOUtil
                   , ListMap
                   , Sort
                   , Yices
                   , YicesFFI
                   , STP
                   , STPFFI
                   , HTcl
                   , BlueTcl
                   , Parser.BSV.CVParser
                   , Parser.BSV.CVParserCommon
                   , Parser.BSV.CVParserImperative
                   , Parser.BSV.CVParserAssertion
                   , Parser.BSV.CVParserUtil
                   , CPackageTime
                   , GitInfo
    other-modules:    ADumpSchedule
                   , BinParse
                   , BinUtil
                   , BluesimLoader
                   , CPPLineDirectives
                   , Depend
                   , FlagsDecode
                   , GenBin
                   , GenFuncWrap
                   , GlobPattern
                   , MVarStrict
                   , Parse
                   , Parser.BSV
                   , Parser.Classic
                   , Parser.Classic.CParser
                   , Parser.Classic.Warnings
                   , SystemVerilogPreprocess
                   , SystemVerilogScanner
                   , TmpNam
                   , AAddSchedAssumps
                   , AAddScheduleDefs
                   , ACheck
                   , ACleanup
                   , ADropDefs
                   , ADropUndet
                   , ANoInline
                   , APaths
                   , AProofs
                   , ARankMethCalls
                   , ARemoveAssumps
                   , ARenameIO
                   , ASchedule
                   , AState
                   , ATaskSplice
                   , AVeriQuirks
                   , AVerilog
                   , BuildSystem
                   , DOT
                   , DPIWrappers
                   , Deriving
                   , DisjointTest
                   , EquivalenceClass
                   , Exceptions
                   , FixupDefs
                   , GenForeign
                   , GenSign
                   , GenWrap
                   , GraphPaths
                   , IDropRules
                   , IExpand
                   , IExpandUtils
                   , IInlineFmt
                   , ILift
                   , ISimplify
                   , ISplitIf
                   , ISyntaxCheck
                   , ISyntaxXRef
                   , InlineWires
                   , LambdaCalc
                   , Libs.Parse

executable bsc
    import:           common-options
    hs-source-dirs:   src/exec
    main-is:          Main.hs
    build-depends:    bsc
                   , base ==4.13.0.0
                   , directory ==1.3.6.0
                   , filepath ==1.4.2.1
                   , process ==1.6.9.0
                   , unix ==2.7.2.2
                   , gitrev >=1.3.1
                   , array ==0.5.4.0
                   , containers ==0.6.2.1
                   , mtl ==2.2.2
                   , parsec ==3.1.14.0
                   , split ==0.2.5
                   , text ==1.2.4.0
                   , bytestring ==0.10.10.1
                   , regex-compat ==0.95.2.2
                   , old-time ==1.1.0.4
                   , time ==1.9.3
                   , integer-gmp ==1.0.2.0

executable bluetcl
    import:           common-options
    hs-source-dirs:   src/bluetcl src/comp
    c-sources: src/vendor/htcl/haskell.c
    main-is:          Main.hs
    build-depends:    bsc
                   , base ==4.13.0.0
                   , directory ==1.3.6.0
                   , filepath ==1.4.2.1
                   , process ==1.6.9.0
                   , unix ==2.7.2.2
                   , gitrev >=1.3.1
                   , array ==0.5.4.0
                   , containers ==0.6.2.1
                   , mtl ==2.2.2
                   , parsec ==3.1.14.0
                   , split ==0.2.5
                   , text ==1.2.4.0
                   , bytestring ==0.10.10.1
                   , regex-compat ==0.95.2.2
                   , old-time ==1.1.0.4
                   , time ==1.9.3
                   , integer-gmp ==1.0.2.0
    extra-libraries:  tcl
                    , htcl
    build-tool-depends: hsc2hs:hsc2hs
    other-modules:    BlueTcl

test-suite bsc-test
    import:           common-options
    type:            exitcode-stdio-1.0
    hs-source-dirs:  testsuite
    main-is:         TestMain.hs
    build-depends:    base ==4.13.0.0
                    , array ==0.5.4.0
                    , containers ==0.6.2.1
                    , directory ==1.3.6.0
                    , filepath ==1.4.2.1
                    , mtl ==2.2.2
                    , parsec ==3.1.14.0
                    , process ==1.6.9.0
                    , syb ==0.7.2.4
                    , unix ==2.7.2.2
                    , split ==0.2.5
                    , text ==1.2.4.0
                    , bytestring ==0.10.10.1
                    , regex-compat ==0.95.2.2
                    , old-time ==1.1.0.4
                    , time ==1.9.3
                    , integer-gmp ==1.0.2.0
                    , bsc
                    , tasty
                    , tasty-hunit
                    , tasty-quickcheck
                    , optparse-applicative ==0.15.1.0

test-suite dejagnu-tests
    import:           common-options
    type:            exitcode-stdio-1.0
    main-is:         TestMain.hs
    hs-source-dirs:  testsuite
    other-modules:   DejaGNUDriver
                   , DejaGNUTest
    build-depends:    base ==4.13.0.0
                    , array ==0.5.4.0
                    , containers ==0.6.2.1
                    , directory ==1.3.6.0
                    , filepath ==1.4.2.1
                    , mtl ==2.2.2
                    , parsec ==3.1.14.0
                    , process ==1.6.9.0
                    , syb ==0.7.2.4
                    , unix ==2.7.2.2
                    , split ==0.2.5
                    , text ==1.2.4.0
                    , bytestring ==0.10.10.1
                    , regex-compat ==0.95.2.2
                    , old-time ==1.1.0.4
                    , time ==1.9.3
                    , integer-gmp ==1.0.2.0
                    , bsc
                    , Cabal >=3.0
                    , tasty
                    , tasty-hunit
                    , tasty-quickcheck
                    , optparse-applicative ==0.15.1.0
