cabal-version:      3.0
name:               bsc
version:            2024.3.0
synopsis:          Bluespec Compiler
description:       The Bluespec Compiler (BSC) is a compiler and simulator for the Bluespec Hardware Description Language.
homepage:          https://github.com/B-Lang-org/bsc
bug-reports:       https://github.com/B-Lang-org/bsc/issues
license:           BSD-3-Clause
license-file:      LICENSE.txt
author:            Bluespec Inc.
maintainer:        B-Lang Maintainers
category:          Hardware
build-type:        Custom
extra-doc-files:   README.md
                   INSTALL.md
                   DEVELOP.md
tested-with:       GHC == 9.8.1
extra-source-files: testsuite/config/*.tcl
                   testsuite/lib/*.exp
                   testsuite/bsc.evaluator/**/*.exp
                   testsuite/bsc.typechecker/**/*.exp
                   testsuite/bsc.lib/**/*.exp
                   testsuite/bsc.if/**/*.exp
                   testsuite/bsc.names/**/*.exp
                   testsuite/bsc.bluetcl/**/*.exp
                   testsuite/bsc.interra/**/*.exp
                   testsuite/bsc.bluesim/**/*.exp
                   testsuite/bsc.bugs/bluespec_inc/**/*.exp
                   testsuite/bsc.bugs/github/**/*.exp
                   testsuite/bsc.bugs/pre_bluespec_inc/**/*.exp
                   testsuite/site.exp
                   src/Libraries/Base1/*.bs
                   src/Libraries/Base1/*.bsv
                   src/Libraries/Base2/*.bs
                   src/Libraries/Base2/*.bsv
                   src/Libraries/Base3-Contexts/*.bs
                   src/Libraries/Base3-Contexts/*.bsv
                   src/Libraries/Base3-Math/*.bs
                   src/Libraries/Base3-Math/*.bsv
                   src/Libraries/Base3-Misc/*.bs
                   src/Libraries/Base3-Misc/*.bsv
                   src/bluetcl/*.tcl

common common-options
    default-language: Haskell2010
    ghc-options:      -Wall
                      -Wcompat
                      -Widentities
                      -Wno-incomplete-uni-patterns
                      -Wno-incomplete-record-updates
                      -fno-warn-orphans
                      -fno-warn-name-shadowing
                      -fno-warn-unused-matches
                      -Wno-dodgy-imports
    if impl(ghc >= 8.0)
        ghc-options:    -Wredundant-constraints
    if impl(ghc >= 8.2)
        ghc-options:    -fhide-source-paths
    if impl(ghc >= 8.4)
        ghc-options:    -Wmissing-export-lists
                        -Wno-partial-fields
    if impl(ghc >= 8.10)
        ghc-options:    -Wunused-packages

custom-setup
    setup-depends: base >= 4.20.0.0 && <4.21
                , Cabal >= 3.0.0.0
                , directory >= 1.3.6.0
                , filepath >= 1.4.2.1
                , process >= 1.6.9.0
                , unix >= 2.7.2.2 && <2.8

library
    import:           common-options
    hs-source-dirs:   src/comp
                      src/Libraries/Base1
                      src/Libraries/Base2
                      src/Libraries/Base3-Math
                      src/Libraries/Base3-Misc
                      src/Libraries/Base3-Contexts
                      src/comp/Libs
                      src/comp/GHC/posix
                      src/comp/Parser/BSV
                      src/vendor/htcl
    build-depends:    base >=4.20.0.0 && <4.21
                   , array >=0.5.4.0 && <0.6
                   , containers >=0.6.2.1 && <0.7
                   , directory >=1.3.6.0 && <1.4
                   , filepath >=1.4.2.1 && <1.5
                   , mtl >=2.2.2 && <2.3
                   , parsec >=3.1.14.0 && <3.2
                   , process >=1.6.9.0 && <1.7
                   , syb >=0.7.2.4 && <0.8
                   , unix >=2.7.2.2 && <2.8
                   , split >=0.2.5 && <0.3
                   , text >=1.2.4.0 && <1.3
                   , bytestring >=0.10.10.1 && <0.12
                   , regex-compat >=0.95.2.2 && <0.96
                   , old-time >=1.1.0.4 && <1.2
                   , time >=1.9.3 && <1.10
                   , gitrev >=1.3.1
                   , sbv ==11.3
                   , syb >=0.7.2.4 && <0.8
                   , htcl
    include-dirs: src/vendor/htcl
    extra-lib-dirs: src/vendor/htcl
    extra-libraries: HSrts-1.0.2
                   , ffi
                   , tcl8.6
                   , tcl9.0
                   , tclstub
                   , HShtcl-0.1.0.0-inplace
    data-dir: src/Libraries
    data-files: Base1/*.bs
                Base1/*.bsv
                Base2/*.bs
                Base2/*.bsv
                Base3-Contexts/*.bs
                Base3-Contexts/*.bsv
                Base3-Math/*.bs
                Base3-Math/*.bsv
                Base3-Misc/*.bs
                Base3-Misc/*.bsv
    extra-tmp-files: build/bsvlib/*.bo
                    build/bsvlib/*.bi
                    build/bsvlib/*.ba
                    build/tcllib/bluespec/tclIndex
                    build/tcllib/bluespec/pkgIndex.tcl
    exposed-modules:  BSC
                   , Util
                   , VCD
                   , VFileName
                   , VFinalCleanup
                   , VIOProps
                   , VModInfo
                   , VPIWrappers
                   , VPrims
                   , VVerilogDollar
                   , Verilog
                   , Version
                   , Wires
                   , TCMisc
                   , TCPat
                   , TCheck
                   , TIMonad
                   , TclUtils
                   , TopUtils
                   , Type
                   , TypeAnalysis
                   , TypeAnalysisTclUtil
                   , TypeCheck
                   , TypeOps
                   , Undefined
                   , SimPrimitiveModules
                   , Simplify
                   , SpeedyString
                   , StdPrel
                   , Subst
                   , SymTab
                   , Synthesize
                   , SystemCWrapper
                   , SystemCheck
                   , SimCCBlock
                   , SimCOpt
                   , SimDomainInfo
                   , SimExpand
                   , SimFileUtils
                   , SimMakeCBlocks
                   , SimPackage
                   , SimPackageOpt
                   , Pretty
                   , Prim
                   , ProofObligation
                   , RSchedule
                   , RealUtil
                   , SAL
                   , SAT
                   , SATPred
                   , SCC
                   , SEMonad
                   , SchedInfo
                   , Scheme
                   , SignalNaming
                   , SimBlocksToC
                   , PoisonUtils
                   , Position
                   , Pragma
                   , PragmaCheck
                   , PreIds
                   , PreStrings
                   , Pred
                   , Pred2SBV
                   , PVPrint
                   , Params
                   , ParseOp
                   , Lex
                   , Literal
                   , Log2
                   , MakeSymTab
                   , PFPrint
                   , PPrint
                   , IWireSet
                   , Id
                   , IdPrint
                   , IfcBetterInfo
                   , InferKind
                   , InlineCReg
                   , InlineReg
                   , ABin
                   , ABinUtil
                   , AConv
                   , ADumpScheduleInfo
                   , AExpand
                   , AExpr2Util
                   , AOpt
                   , AScheduleInfo
                   , ASyntax
                   , ASyntaxUtil
                   , AUses
                   , AVerilogUtil
                   , Assump
                   , BDD
                   , BExpr
                   , Backend
                   , BackendNamingConventions
                   , Bag
                   , Balanced
                   , BinData
                   , BoolExp
                   , BoolOpt
                   , BuildVersion
                   , CCSyntax
                   , CFreeVars
                   , CSubst
                   , CSyntax
                   , CSyntaxTypes
                   , CSyntaxUtil
                   , CType
                   , CVPrint
                   , Classic
                   , ConTagInfo
                   , ContextErrors
                   , CtxRed
                   , Error
                   , ErrorUtil
                   , ErrorMonad
                   , Eval
                   , FStringCompat
                   , FileIOUtil
                   , FileNameUtil
                   , Fixity
                   , Flags
                   , ForeignFunctions
                   , GHCPretty
                   , GenABin
                   , GenWrapUtils
                   , GraphMap
                   , GraphUtil
                   , GraphWrapper
                   , IConv
                   , IConvLet
                   , IInline
                   , IInlineUtil
                   , IOMutVar
                   , IPrims
                   , IStateLoc
                   , ISyntax
                   , ISyntaxUtil
                   , ITransform
                   , IType
                   , InstNodes
                   , IntLit
                   , IntegerUtil
                   , Intervals
                   , KIMisc
                   , LambdaCalcUtil
                   , SystemVerilogKeywords
                   , SystemVerilogTokens
                   , Unify
                   , IOUtil
                   , ListMap
                   , Sort
                   , HTcl
                   , BlueTcl
                   , Parser.BSV.CVParser
                   , Parser.BSV.CVParserCommon
                   , Parser.BSV.CVParserImperative
                   , Parser.BSV.CVParserAssertion
                   , Parser.BSV.CVParserUtil
                   , CPackageTime
                   , GitInfo
    other-modules:    ADumpSchedule
                   , AExpr2SBV
                   , BinParse
                   , BinUtil
                   , BluesimLoader
                   , CPPLineDirectives
                   , Depend
                   , FlagsDecode
                   , GenBin
                   , GenFuncWrap
                   , GlobPattern
                   , MVarStrict
                   , Parse
                   , Parser.BSV
                   , Parser.Classic
                   , Parser.Classic.CParser
                   , Parser.Classic.Warnings
                   , SystemVerilogPreprocess
                   , SystemVerilogScanner
                   , TmpNam
                   , AAddSchedAssumps
                   , AAddScheduleDefs
                   , ACheck
                   , ACleanup
                   , ADropDefs
                   , ADropUndet
                   , ANoInline
                   , APaths
                   , AProofs
                   , ARankMethCalls
                   , ARemoveAssumps
                   , ARenameIO
                   , ASchedule
                   , AState
                   , ATaskSplice
                   , AVeriQuirks
                   , AVerilog
                   , BuildSystem
                   , DOT
                   , DPIWrappers
                   , Deriving
                   , DisjointTest
                   , EquivalenceClass
                   , Exceptions
                   , FixupDefs
                   , GenForeign
                   , GenSign
                   , GenWrap
                   , GraphPaths
                   , IDropRules
                   , IExpand
                   , IExpandUtils
                   , IInlineFmt
                   , ILift
                   , ISimplify
                   , ISplitIf
                   , ISyntaxCheck
                   , ISyntaxXRef
                   , InlineWires
                   , LambdaCalc
                   , Libs.Parse

executable bsc
    import:           common-options
    hs-source-dirs:   src/exec
    main-is:          Main.hs
    build-depends:    bsc
                   , base >=4.20.0.0 && <4.21
                   , directory >=1.3.6.0 && <1.4
                   , filepath >=1.4.2.1 && <1.5
                   , process >=1.6.9.0 && <1.7
                   , unix >=2.7.2.2 && <2.8
                   , gitrev >=1.3.1
                   , array >=0.5.4.0 && <0.6
                   , containers >=0.6.2.1 && <0.7
                   , mtl >=2.2.2 && <2.3
                   , parsec >=3.1.14.0 && <3.2
                   , split >=0.2.5 && <0.3
                   , text >=1.2.4.0 && <1.3
                   , bytestring >=0.10.10.1 && <0.12
                   , regex-compat >=0.95.2.2 && <0.96
                   , old-time >=1.1.0.4 && <1.2
                   , time >=1.9.3 && <1.10
                   , integer-gmp >=1.0.2.0 && <1.2
    extra-libraries: HSrts-1.0.2
                    , ffi
                    , tcl8.6
                    , tcl9.0
                    , tclstub
                    , HShtcl-0.1.0.0-inplace
    include-dirs: ${pkgroot}/src/vendor/htcl
    extra-lib-dirs: ${pkgroot}/src/vendor/htcl

executable bluetcl
    import:           common-options
    hs-source-dirs:   src/bluetcl src/comp
    c-sources: src/vendor/htcl/haskell.c
    main-is:          Main.hs
    build-depends:    bsc
                   , base >=4.20.0.0 && <4.21
                   , directory >=1.3.6.0 && <1.4
                   , filepath >=1.4.2.1 && <1.5
                   , process >=1.6.9.0 && <1.7
                   , unix >=2.7.2.2 && <2.8
                   , gitrev >=1.3.1
                   , array >=0.5.4.0 && <0.6
                   , containers >=0.6.2.1 && <0.7
                   , mtl >=2.2.2 && <2.3
                   , parsec >=3.1.14.0 && <3.2
                   , split >=0.2.5 && <0.3
                   , text >=1.2.4.0 && <1.3
                   , bytestring >=0.10.10.1 && <0.12
                   , regex-compat >=0.95.2.2 && <0.96
                   , old-time >=1.1.0.4 && <1.2
                   , time >=1.9.3 && <1.10
                   , integer-gmp >=1.0.2.0 && <1.2
                   , syb >=0.7.2.4 && <0.8
                   , sbv ==11.3
                   , generic-data >=1.0.0
    extra-libraries: HSrts-1.0.2
                    , ffi
                    , tcl8.6
                    , tcl9.0
                    , tclstub
                    , HShtcl-0.1.0.0-inplace
    include-dirs: ${pkgroot}/src/vendor/htcl
    extra-lib-dirs: ${pkgroot}/src/vendor/htcl
    build-tool-depends: hsc2hs:hsc2hs
    other-modules:    BlueTcl

test-suite bsc-tests
    type:                exitcode-stdio-1.0
    main-is:            TestMain.hs
    hs-source-dirs:     testsuite
    build-depends:      base >=4.20.0.0 && <4.21
                     , directory >=1.3.6.0 && <1.4
                     , filepath >=1.4.2.1 && <1.5
                     , process >=1.6.9.0 && <1.7
                     , bsc
                     , tasty
                     , tasty-hunit
                     , optparse-applicative >=0.15.1.0 && <0.16
    extra-source-files: testsuite/config/*.tcl
                     , testsuite/lib/*.exp
                     , testsuite/bsc.evaluator/**/*.exp
                     , testsuite/bsc.typechecker/**/*.exp
                     , testsuite/bsc.lib/**/*.exp
                     , testsuite/bsc.if/**/*.exp
                     , testsuite/bsc.names/**/*.exp
                     , testsuite/bsc.bluetcl/**/*.exp
                     , testsuite/bsc.interra/**/*.exp
                     , testsuite/bsc.bluesim/**/*.exp
                     , testsuite/bsc.bugs/bluespec_inc/**/*.exp
                     , testsuite/bsc.bugs/github/**/*.exp
                     , testsuite/bsc.bugs/pre_bluespec_inc/**/*.exp
                     , testsuite/site.exp
    data-files:         testsuite/config/*.tcl
                     , testsuite/lib/*.exp
                     , testsuite/bsc.evaluator/**/*.exp
                     , testsuite/bsc.typechecker/**/*.exp
                     , testsuite/bsc.lib/**/*.exp
                     , testsuite/bsc.if/**/*.exp
                     , testsuite/bsc.names/**/*.exp
                     , testsuite/bsc.bluetcl/**/*.exp
                     , testsuite/bsc.interra/**/*.exp
                     , testsuite/bsc.bluesim/**/*.exp
                     , testsuite/bsc.bugs/bluespec_inc/**/*.exp
                     , testsuite/bsc.bugs/github/**/*.exp
                     , testsuite/bsc.bugs/pre_bluespec_inc/**/*.exp
                     , testsuite/site.exp
    default-language:   Haskell2010
    ghc-options:        -Wall
                      -Wcompat
                      -Widentities
                      -Wno-incomplete-uni-patterns
                      -Wno-incomplete-record-updates
                      -fno-warn-orphans
                      -fno-warn-name-shadowing
                      -fno-warn-unused-matches
                      -Wno-dodgy-imports

if os(darwin)
    if arch(aarch64)
        cc-options: -arch arm64
        ld-options: -arch arm64
    else
        cc-options: -arch x86_64
        ld-options: -arch x86_64

data-files:     src/Libraries/Base1/*.bs
                src/Libraries/Base1/*.bsv
                src/Libraries/Base2/*.bs
                src/Libraries/Base2/*.bsv
                src/Libraries/Base3-Contexts/*.bs
                src/Libraries/Base3-Contexts/*.bsv
                src/Libraries/Base3-Math/*.bs
                src/Libraries/Base3-Math/*.bsv
                src/Libraries/Base3-Misc/*.bs
                src/Libraries/Base3-Misc/*.bsv
                src/bluetcl/*.tcl

extra-tmp-files: build/bsvlib/*.bo
                build/bsvlib/*.bi
                build/bsvlib/*.ba
                build/tcllib/bluespec/tclIndex
                build/tcllib/bluespec/pkgIndex.tcl

build-type:     Custom

test-suite unit-tests
    import:           common-options
    type:            exitcode-stdio-1.0
    hs-source-dirs:  testsuite
    main-is:         TestMain.hs
    other-modules:   DejaGNUDriver
                   , DejaGNUTest
    build-depends:    base >=4.20.0.0 && <4.21
                    , array >=0.5.4.0 && <0.6
                    , containers >=0.6.2.1 && <0.7
                    , directory >=1.3.6.0 && <1.4
                    , filepath >=1.4.2.1 && <1.5
                    , mtl >=2.2.2 && <2.3
                    , parsec >=3.1.14.0 && <3.2
                    , process >=1.6.9.0 && <1.7
                    , syb >=0.7.2.4 && <0.8
                    , unix >=2.7.2.2 && <2.8
                    , split >=0.2.5 && <0.3
                    , text >=1.2.4.0 && <1.3
                    , bytestring >=0.10.10.1 && <0.12
                    , regex-compat >=0.95.2.2 && <0.96
                    , old-time >=1.1.0.4 && <1.2
                    , time >=1.9.3 && <1.10
                    , integer-gmp >=1.0.2.0 && <1.2
                    , bsc
                    , tasty
                    , tasty-hunit
                    , tasty-quickcheck
                    , optparse-applicative >=0.15.1.0 && <0.16
    include-dirs: /opt/homebrew/Cellar/tcl-tk@8/8.6.16/include
                 , /opt/homebrew/Cellar/tcl-tk/9.0.1/include/tcl-tk
                 , /Users/npe/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/lib/aarch64-osx-ghc-9.10.1/rts-1.0.2/include
                 , /opt/homebrew/include
                 , /Users/npe/src/bsc-new/bsc/src/vendor/htcl/include
    extra-lib-dirs: /opt/homebrew/Cellar/tcl-tk@8/8.6.16/lib
                   , /opt/homebrew/Cellar/tcl-tk/9.0.1/lib
                   , /Users/npe/.ghcup/ghc/9.10.1/lib/ghc-9.10.1/lib/aarch64-osx-ghc-9.10.1/rts-1.0.2
                   , /opt/homebrew/opt/libffi/lib
                   , /Users/npe/src/bsc-new/bsc/dist-newstyle/build/aarch64-osx/ghc-9.10.1/htcl-0.1.0.0/opt/build
    extra-libraries: HSrts-1.0.2
                    , ffi
                    , tcl8.6
                    , tcl9.0
                    , tclstub
                    , HShtcl-0.1.0.0-inplace
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    build-tool-depends: hsc2hs:hsc2hs
