name: CI

# Trigger the workflow on push or pull request
on: [ push, pull_request ]

jobs:
  # Wait for Docker images to be built
  wait-for-docker:
    name: "Wait for Docker images"
    runs-on: ubuntu-latest
    steps:
      - name: Wait for Docker build
        uses: lewagon/wait-on-check-action@v1.3.1
        with:
          ref: ${{ github.ref }}
          check-name: 'Build Docker Images'
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          wait-interval: 10

  # ------------------------------
  # Basic linting requirements for new commits

  build-check-src:
    name: "Check: code cleanliness"
    needs: [wait-for-docker]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-deps:ubuntu-24.04
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: read
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Check tabs and whitespace
        shell: bash
        run: ".github/workflows/check_whitespace.sh"

  build-check-testsuite:
    name: "Check: testsuite lint"
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-deps:ubuntu-24.04
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: read
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4
      - name: Check CONFDIR
        run: |
          cd testsuite
          ../.github/workflows/check_confdir.py
          ../.github/workflows/check_symlinks.py

  # ------------------------------
  # Builds for release, using a reliable and stable version of GHC

  build-and-test-ubuntu:
    name: "Build/Test: ubuntu-${{ matrix.os }}"
    needs: [build-check-src, build-check-testsuite]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-ghc:ubuntu-${{ matrix.os }}-9.6.7
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: read
    strategy:
      matrix:
        os: [ '22.04', '24.04' ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          CCACHE_DIR: /ccache
        run: |
          ccache --zero-stats --max-size 250M
          export PATH=/usr/lib/ccache:$PATH
          make -j3 GHCJOBS=2 GHCRTSFLAGS='+RTS -M5G -A128m -RTS' install-src
          tar czf inst.tar.gz inst
      - name: CCache stats
        env:
          CCACHE_DIR: /ccache
        run: ccache --show-stats
      - name: Smoketest
        run: "make check-smoke"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-${{ matrix.os }} build
          path: inst.tar.gz

  # ------------------------------
  # Tests using other recent versions of GHC

  build-and-test-ghc-ubuntu:
    name: "Build/Test: GHC Ubuntu"
    needs: [build-check-src, build-check-testsuite]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-ghc:ubuntu-22.04-${{ matrix.ghc.version }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: read
    strategy:
      matrix:
        ghc:
          - version: '9.4.8'
            hls: '2.10.0.0'
          - version: '9.8.4'
            hls: '2.10.0.0'
          - version: '9.10.1'
            hls: '2.10.0.0'
          - version: '9.12.2'
            hls: '2.10.0.0'
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          CCACHE_DIR: /ccache
        run: |
          ccache --zero-stats --max-size 250M
          export PATH=/usr/lib/ccache:$PATH
          make -j3 GHCJOBS=2 GHCRTSFLAGS='+RTS -M5G -A128m -RTS' install-src
          tar czf inst.tar.gz inst
      - name: CCache stats
        env:
          CCACHE_DIR: /ccache
        run: ccache --show-stats
      - name: Smoketest
        run: "make check-smoke"
      - name: Test Haskell Language Server
        if: ${{ matrix.ghc.hls != '' }}
        run: |
          python3 util/haskell-language-server/gen_hie.py
          pushd src/comp
          haskell-language-server-${{ matrix.ghc.version }} bsc.hs
          popd
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-22.04-ghc-${{ matrix.ghc.version }} build
          path: inst.tar.gz

  # ------------------------------
  # Test the building of documentation

  build-doc-ubuntu:
    name: "Build doc: ubuntu-${{ matrix.os }}"
    needs: [build-check-src, build-check-testsuite]
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}-deps:ubuntu-${{ matrix.os }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: read
      packages: read
    strategy:
      matrix:
        os: [ '22.04', '24.04' ]
      fail-fast: false
    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: |
          make -j3 install-doc
          tar czf inst.tar.gz inst
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-${{ matrix.os }} build doc
          path: inst.tar.gz
      - name: Upload doc not tar
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-${{ matrix.os }}-doc-not-tar
          path: inst/doc
